version: '3'
services:
  tech-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
      - rabbitmq

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "unique-cookie-value"